import typing
import uuid

from microarch.delivery.core.domain.model.order.order import Order


class IOrderrepository(typing.Protocol):
    async def add(self, order: Order) -> None: ...
    async def update(self, order: Order) -> None: ...
    async def get_by_id(self, id_: uuid.UUID) -> Order | None: ...
    async def get_created_order(self) -> Order | None: ...
    async def get_assigned_orders(self) -> typing.Iterable[Order]: ...
